# Generated by Django 4.2.17 on 2024-12-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0002_remove_exerciseplan_price"),
        ("products", "0001_initial"),
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan.plan",
            ),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
