# Generated by Django 4.2.17 on 2024-12-21 18:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_orderlineitem_plan_alter_orderlineitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
