# Generated by Django 4.2.17 on 2024-12-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "sku",
                    models.CharField(
                        default="SKU-DEFAULT", max_length=100, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipment"),
                            ("nutrition", "Nutrition"),
                            ("merchandise", "Merchandise"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "has_sizes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
